version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    networks:
      - app-tier
    ports:
      - 3306:3306 
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword 
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testtest
      - MYSQL_DATABASE=main 
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-tier:
    driver: bridge